<?php

define("DB_HOST", "127.0.0.1");
define("DB_USERNAME", "PIZZERIA");
define("DB_PASSWORD", "tC)L27T@sUuYnw92");
define("DB_DATABASE_NAME", "PIZZERIA");

define("HTTP_V", "HTTP/1.1");



/**DEFINIZIONE DELLE TABELLE*/

//ALLERGENE
define("DB_ALLERGENE", "ALLERGENE");
define("DB_ALLERGENE_ETICHETTA", "ETICHETTA");

//TIPO AGGIUNTA
define("DB_TIPOAGGIUNTA", "TIPO_AGGIUNTA");
define("DB_TIPOAGGIUNTA_ETICHETTA", 'ETICHETTA');

//AGGIUNTA
define("DB_AGGIUNTA", "AGGIUNTA");
define("DB_AGGIUNTA_NOME", "NOME");
define("DB_AGGIUNTA_PREZZO", "PREZZO");

//PIZZA
define("DB_PIZZA", "PIZZA");
define("DB_PIZZA_IDHASH", "ID_HASH");
define("DB_PIZZA_NOME", "NOME");
define("DB_PIZZA_PREZZO", "PREZZO");

//PIZZA_AGGIUNTA
define("DB_PIZZAAGGIUNTA", "PIZZA_AGGIUNTA");
define("DB_PIZZAAGGIUNTA_IDPIZZA", "ID_PIZZA");
define("DB_PIZZAAGGIUNTA_IDAGGIUNTA", "ID_AGGIUNTA");

//PIZZA ALLERGENE
define("DB_AGGIUNTAALLERGENE", "AGGIUNTA_ALLERGENE");
define("DB_AGGIUNTAALLERGENE_IDAGGIUNTA", "ID_AGGIUNTA");
define("DB_AGGIUNTAALLERGENE_IDALLERGENE", "ID_ALLERGENE");

//PRENOTAZIONE
define("DB_PRENOTAZIONE", "PRENOTAZIONE");
define("DB_PRENOTAZIONE_NOME", "NOME"); //Nome alla quale è stato prenotato
define("DB_PRENOTAZIONE_DATAPRENOTAZIONE", "DATA_PRENOTAZIONE");
define("DB_PRENOTAZIONE_DATAAVVENIMENTO", "DATA_AVVENIMENTO");
define("DB_PRENOTAZIONE_STATO", "STATO");
define("DB_PRENOTAZIONE_NUMEROPERSONE", "NUMERO_PERSONE");
define("DB_PRENOTAZIONE_TIPO", "TIPO");
define("DB_PRENOTAZIONE_DESCRIZIONESTATO", "DESCRIZIONE_STATO");
define("DB_PRENOTAZIONE_IDTAVOLO", "ID_TAVOLO");
define("DB_PRENOTAZIONE_USERID", "USER_ID");
define("DB_PRENOTAZIONE_TELEFONO", "TELEFONO");

//ORDINE
define("DB_ORDINE", "ORDINE");
define("DB_ORDINE_IDPRENOTAZIONE", "ID_PRENOTAZIONE");
define("DB_ORDINE_IDPIZZA", "ID_PIZZA");

define("DB_ORDINEAGGIUNTA", "ORDINE_AGGIUNTA");
define("DB_ORDINE_IDORDINE", "ID_ORDINE");
define("DB_ORDINE_IDAGGIUNTA", "ID_AGGIUNTA");



/**DEFINIZIONE DEI MODULI**/
define("MODULE_ALLERGENE", "allergene");
define("MODULE_PIZZA", "pizza");
define("MODULE_AGGIUNTA", "aggiunta");
define("MODULE_TIPOAGGIUNTA", "tipoaggiunta");
define("MODULE_PRENOTAZIONE", "prenotazione");


define("PRENOTAZIONE_STATO_BOZZA", 0);
define("PRENOTAZIONE_STATO_CONFERMATO", 1);
define("PRENOTAZIONE_STATO_RIFIUTATO", 2);
define("PRENOTAZIONE_STATO_ELIMINATO", 3);

define("COOKIE_NAME" , "usrcok");