CREATE DATABASE PIZZERIA;
USE PIZZERIA;
CREATE TABLE TIPO_AGGIUNTA ( 
    ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
    ID_HASH VARCHAR(64) UNIQUE, 
    ETICHETTA VARCHAR(128) UNIQUE NOT NULL
);

-- Creo la tabella Aggiunta
-- PREZZO FLOAT(5,2) -> Float con 5 cifre di cui 2 decimale (i centesimi)
CREATE TABLE AGGIUNTA (
    ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
    ID_HASH VARCHAR(64) UNIQUE,
    NOME VARCHAR(255) NOT NULL UNIQUE, 
    PREZZO FLOAT(5,2) NOT NULL, 
    QUANTITA INTEGER UNSIGNED NOT NULL,
    ID_TIPO_AGGIUNTA BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (ID_TIPO_AGGIUNTA) REFERENCES TIPO_AGGIUNTA(ID)
);

-- Creo la tabella Allergene
CREATE TABLE ALLERGENE(
    ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ID_HASH VARCHAR(64) UNIQUE,
    ETICHETTA VARCHAR(1024) NOT NULL
);


-- Creo la tabella Aggiuna-Allergene per la N-N tra Aggiunta e Allergene
CREATE TABLE AGGIUNTA_ALLERGENE(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ID_AGGIUNTA BIGINT UNSIGNED NOT NULL,
    ID_ALLERGENE BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (ID_AGGIUNTA) REFERENCES AGGIUNTA(ID),
    FOREIGN KEY (ID_ALLERGENE) REFERENCES ALLERGENE(ID)
);

-- Creo la tabella Pizza
-- PREZZO FLOAT(4,2) -> Float con 4 cifre di cui 2 decimale (i centesimi)
CREATE TABLE PIZZA(
    ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ID_HASH VARCHAR(64) UNIQUE,
    NOME VARCHAR(64) NOT NULL,
    PREZZO FLOAT(4,2) NOT NULL
);


-- Creo la tabella Aggiuna-Allergene per la N-N tra Aggiunta e Allergene
CREATE TABLE PIZZA_AGGIUNTA(
    ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ID_AGGIUNTA BIGINT UNSIGNED NOT NULL,
    ID_PIZZA BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (ID_AGGIUNTA) REFERENCES AGGIUNTA(ID),
    FOREIGN KEY (ID_PIZZA) REFERENCES PIZZA(ID),
    CONSTRAINT PIZZA_AGGIUNTA_UNIQUE UNIQUE (ID_AGGIUNTA, ID_PIZZA)
);


CREATE TABLE TAVOLO(
    ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ID_HASH VARCHAR(64) UNIQUE,
    POSTI INTEGER UNSIGNED NOT NULL
);

-- Creo la tabella Prenotazione
-- Data prenotazione è la data in cui il cliente ha prenotato
-- Data avvenimento è la data per la quale il cliente ha prenotato
CREATE TABLE PRENOTAZIONE(
    ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ID_HASH VARCHAR(64) UNIQUE,
    NOME VARCHAR(64) NOT NULL,
    DATA_PRENOTAZIONE DATE NOT NULL,
    DATA_AVVENIMENTO DATE NOT NULL, 
    STATO ENUM('0','1','2'), -- (0: ELABORAZIONE, 1: CONFERMATO, 2: RIFIUTATO)
    ID_TAVOLO BIGINT UNSIGNED,
    NUMERO_PERSONE INTEGER UNSIGNED NOT NULL,
    TIPO ENUM('0','1') NOT NULL, -- Asporto o tavolo, se tavolo ID_TAVOLO non può essere null
    DESCRIZIONE_STATO VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(512) NOT NULL, 
    TELEFONO BIGINT UNSIGNED,
    FOREIGN KEY (ID_TAVOLO) REFERENCES TAVOLO(ID)
);

-- Creo la tabella Ordine che rappresenta l'ordine si un singolo cliente
CREATE TABLE ORDINE(
    ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ID_HASH VARCHAR(64) UNIQUE,
    ID_PRENOTAZIONE BIGINT UNSIGNED NOT NULL,
    ID_PIZZA BIGINT UNSIGNED,
    FOREIGN KEY (ID_PRENOTAZIONE) REFERENCES PRENOTAZIONE(ID),
    FOREIGN KEY (ID_PIZZA) REFERENCES PIZZA(ID)
);

CREATE TABLE ORDINE_AGGIUNTA(
    ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ID_HASH VARCHAR(64) UNIQUE,
    ID_ORDINE BIGINT UNSIGNED NOT NULL,
    ID_AGGIUNTA BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (ID_ORDINE) REFERENCES ORDINE(ID),
    FOREIGN KEY (ID_AGGIUNTA) REFERENCES AGGIUNTA(ID)
);


-- Creo la tabella pe le N-N tra un singolo ordine e gli allergeni, tale tabella mi serve per tener traccia delle allergie di un individuo
CREATE TABLE ORDINE_ALLERGENE(
    ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    ID_HASH VARCHAR(64) UNIQUE,
    ID_ORDINE BIGINT UNSIGNED NOT NULL,
    ID_ALLERGENE BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (ID_ORDINE) REFERENCES ORDINE(ID),
    FOREIGN KEY (ID_ALLERGENE) REFERENCES ALLERGENE(ID)
);


-- Creo la tabella dei ruoli
CREATE TABLE RUOLO(
    ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOME_RUOLO VARCHAR(64) UNIQUE NOT NULL,
    IDENTIFICATIVO INTEGER UNSIGNED UNIQUE NOT NULL
);

-- Creo la tabella dell'anagrafica
CREATE TABLE ANAGRAFICA(
    ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(64) NOT NULL,
    COGNOME VARCHAR(64) NOT NULL,
    USERNAME VARCHAR(64) UNIQUE NOT NULL,
    PSW VARCHAR(128) NOT NULL, -- 128 chars per lo sha512
    ID_RUOLO BIGINT UNSIGNED NOT NULL, 
    FOREIGN KEY (ID_RUOLO) REFERENCES RUOLO(ID)
);

INSERT INTO RUOLO VALUES (NULL, "Cameriere", 1), (NULL, "Magazziniere", 2), (NULL, "Pizzaiolo", 3), (NULL, "Responsabile", 4);
INSERT INTO ANAGRAFICA VALUES
(NULL, "Gabriele", "Pace", "gabriele_pace", SHA2("password", 512), 1),
(NULL, "Maria", "Vitale", "maria_vitale", SHA2("password", 512), 2),
(NULL, "Mario", "Rossi", "mario_rossi", SHA2("password", 512), 3),
(NULL, "Luigi", "Verdi", "luigi_verdi", SHA2("password", 512), 4);